DjangoE_commerce/DjangoE_commerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('DjangoEcommerce.urls')),
    path("",include('django.contrib.auth.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DjangoE_commerce/DjangoEcommerce/urls.py
from django.urls import path
from . import views
app_name='DjangoEcommerce'
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',views.mainpage, name="mainpage" ),
    path('signup/',views.SignUpView.as_view(),name="signup"),
    path('register/',views.register,name="register"),
    path('addproduct/',views.add_product,name="addproduct"),
    path('products/',views.listproducts,name="products"),
    path('deleteproduct/<int:id>',views.DeleteProduct,name='DeleteProduct'),
    path('product_details/<int:product_id>/', views.product_details, name='product_details'),
    path('orderform/', views.orderform, name='orderform'),
    path('cart/', views.cart, name='cart'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    
]

DjangoE_commerce/DjangoEcommerce/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=50)
    price = models.IntegerField()
    image= models.ImageField(upload_to='products/product_images/', null=True, blank=True)
    image2= models.ImageField(upload_to='products/product_images2/', null=True, blank=True)
    image3= models.ImageField(upload_to='products/product_images3/', null=True, blank=True)


    describtion= models.TextField(null=True)
    
    def __str__(self):
        return self.name
    
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return f'{self.quantity} x {self.product.name}'
    
  

    

# Create your models here.

DjangoE_commerce/DjangoEcommerce/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Product
from . models import Order
from . models import CartItem

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class AddProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name',  'price', 'image','image2','image3','describtion']

class OrderForm(forms.ModelForm):
    class Meta:
        model=CartItem
        fields = ['quantity', 'product']

DjangoE_commerce/DjangoEcommerce/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,Http404,HttpResponseNotFound,HttpResponseRedirect
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required 
from django.contrib.auth.forms import UserCreationForm 
from django.views.generic import CreateView
from . import models
from . import forms
from .forms import RegisterForm
from django.core.exceptions import ValidationError
from django.contrib.auth.decorators import login_required
from .forms import AddProductForm
from . forms import OrderForm
from . models import CartItem

# Create your views here.

def mainpage(request):
    return render(request,"DjangoEcommerce/mainpage.html")

def register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")  # Kayıt sonrası yönlendirilecek sayfa
    else:
        form = RegisterForm()
    return render(request, "registration/register.html", context={"form": form})

class SignUpView(CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy("login")
    template_name="registration/signup.html"

def listproducts(request):
    all_products=models.Product.objects.all()
    product_dictionary={"products":all_products}
    return render(request,'DjangoEcommerce/products.html',context=product_dictionary)
    
def product_details(request,product_id):
    product=models.Product.objects.get(pk=product_id)
    return render(request, 'DjangoEcommerce/product_details.html', context={"product": product})


'''
@login_required(login_url="/login")
def add_product(request):
    if request.POST:
        product_name = (request.POST["product_name"])
        product_describtion=(request.POST["product_describtion"])
        product_img=(request.POST["product_img"])
        product_price=(request.POST["product_price"])
        models.AddProduct.objects.create(product_name=product_name,product_describtion=product_describtion,product_img=product_img,product_price=product_price)
        return redirect(reverse('DjangoEcommerce:products'))
    else:
        return render(request, 'DjangoEcommerce/addproduct.html')
'''
@login_required(login_url="/login")
def add_product(request):
    if request.method == "POST":
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            
            name=form.cleaned_data["name"]
            price=form.cleaned_data["price"]
            image=form.cleaned_data["image"]
            image2=form.cleaned_data["image2"]
            image3=form.cleaned_data["image3"]
            describtion=form.cleaned_data["describtion"]
            models.Product.objects.create(name=name,describtion=describtion,image=image,price=price,image2=image2,image3=image3,)
            return redirect(reverse('DjangoEcommerce:products'))
        else:
            print("error in form")
            return render(request,'DjangoEcommerce/addproduct.html',context={"form":form})  
    else:
        form = AddProductForm()
    return render(request, 'DjangoEcommerce/addproduct.html', context={'form': form})
@login_required(login_url="/login")
def DeleteProduct(request,id):

    product=models.Product.objects.get(pk=id)
    
   
    models.Product.objects.filter(id=id).delete()
    return redirect(reverse('DjangoEcommerce:products'))#şimdi bunu urls.py ye tanımlıca


def cart(request):
    
    cart_items = models.CartItem.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    return render(request, 'DjangoEcommerce/cart.html', context={'cart_items': cart_items, 'total_price': total_price})
@login_required(login_url="/login")
def add_to_cart(request,product_id):
    
    product = models.Product.objects.get(id=product_id)
    cart_item, created = models.CartItem.objects.get_or_create(product=product, 
                                                        user=request.user)
    cart_item.quantity += 1
    cart_item.save()
    return redirect(reverse('DjangoEcommerce:cart'))
    

def remove_from_cart(request, item_id):
    cart_item = models.CartItem.objects.get(id=item_id)
    cart_item.delete()
    return redirect('DjangoEcommerce:cart')

def orderform(request):
    
    cart_items = CartItem.objects.filter(user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    item_total_price=print((item.product.price * item.quantity for item in cart_items))

    
    
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.product = cart_item.product
            order.user = request.user
            order.save()
            return redirect('DjangoEcommerce:cart')
            
    else:
        form = OrderForm()

    context = {
        
        'form': OrderForm(),
        'cart_items': cart_items,
        'total_price': total_price,
        'item_total_price':item_total_price,
    }

    return render(request, 'DjangoEcommerce/orderform.html', context=context)

DjangoE_commerce/DjangoEcommerce/templates/DjangoEcommerce/addproduct.html
{%extends 'base.html'%}
{%block content%}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Product</button>
</form>
{%endblock%}

DjangoE_commerce/DjangoEcommerce/templates/DjangoEcommerce/cart.html
{%extends 'base.html'%}

{%block content%}

<style>
    /* Add CSS styles for flex container and items */
    .product-list {
        display: flex;
        flex-wrap: wrap; /* Allow items to wrap to the next row if necessary */
        justify-content: space-between; /* Space items evenly along the main axis */
        list-style: none; /* Remove list styles */
        padding: 0;
    }

    .product-item {
         
        flex: 1; /* Grow to fill available space evenly */
         /* Limit item width to avoid overcrowding */
        margin: 10px; /* Add spacing between items */
        border: 1px solid #ccc; /* Add a border for visual separation */
        padding: 10px;
        text-align: center;
    }

    /* Style the "Buy Now" button */
    .buy-now-button {
        display: block;
        margin-top: 10px;
        background-color: #007bff;
        color: #fff;
        text-decoration: none;
        padding: 5px 10px;
        border-radius: 5px;
    }
</style>
<body>
 
    <h1>Your Shopping Cart</h1>
 
    <div class="product-list">
 
    
 
    {% for item in cart_items %}
    <div class="product-item">
        <p>{{ item.product.name }} ({{ item.quantity }})</p>
        <p>Price: ${{ item.product.price }}</p>
        <a href="{% url 'DjangoEcommerce:remove_from_cart' item.id %}">Remove</a>
    </div>
    {% empty %}
    <p>Your cart is empty.</p>
    
 
    </div>
 
    
    <ul>
        
            <li>{{ item.product.name }} - {{ item.quantity }} x {{ item.product.price }}</li>
            <!-- orderform linki -->
             
            
           
        
    </ul>
{%endfor%}
    <p>Total Price: ${{ total_price }}</p>
   
    <a href="{% url 'DjangoEcommerce:orderform' %}"  class="btn btn-primary">Go to Order Form</a>
    <a href="{% url 'DjangoEcommerce:products' %}"  class="btn btn-primary">Contine Shopping </a>
  
</body>
{%endblock%}

DjangoE_commerce/DjangoEcommerce/templates/DjangoEcommerce/mainpage.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

<div id="carouselExampleCaptions" class="carousel slide">
  <div class="carousel-indicators" style="border: 10px;">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'images/default/sellproduct1.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        
        <p style="background-color: black;">You can sell your products too easier with our.</p>
        
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/default/Sell-products-online.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        
        <p style="background-color: black;">We have a huge customer base soo you should try sell your products with our site.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'images/default/PF_Method__3_.jpg' %}" class="d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        
        <p style="background-color: black;">If you want start workin with our and make more profit you have to signup.</p>
        <p><a class="btn btn-lg btn-primary" href="{%url 'DjangoEcommerce:register' %}">SignUp</a></p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

  <!-- Marketing messaging and featurettes
  ================================================== -->
  <!-- Wrap the rest of the page in another container to center all the content. -->

  <br>

    <!-- START THE FEATURETTES -->

    <hr class="featurette-divider" style="padding: 10px;">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Reach a Wide Customer Base <span class="text-body-secondary">We have 80 percent seller and customer satisfaction.</span></h2>
        <p class="lead">Our site offers a dynamic sales platform where you can meet thousands of potential customers every day. It's an ideal opportunity to introduce your products to a wider audience and increase your sales! Open your store in just a few steps and offer your products to millions of people.</p>
      </div>
      <div class="col-md-5">
        <img src="{% static 'images/default/Customer-Base.png' %}" class="d-block w-100" alt="...">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7 order-md-2">
        <h2 class="featurette-heading fw-normal lh-1">Easy and Safe Sales Experience <span class="text-body-secondary">See for yours potanciel.</span></h2>
        <p class="lead">Our platform is designed to give you an effortless sales process. Listing your products, managing orders and receiving payments has never been easier. Conduct your sales smoothly and focus on growing your business with our reliable infrastructure and user-friendly panel.</p>
      </div>
      <div class="col-md-5 order-md-1">
        <img src="{% static 'images/default/safe.jpg' %}" class="d-block w-100" alt="...">
      </div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">And lastly, this one. <span class="text-body-secondary">Competitive Commission Rates and Support</span></h2>
        <p class="lead">Our site allows you to make sales with affordable commission rates and low costs. While you earn more from your sales, take your business to the next level with our professional support team that is always with you when you need it. By working with us, you can reach your sales goals faster and easier.</p>
      </div>
      <div class="col-md-5">
        <img src="{% static 'images/default/Sales-Commission.webp' %}" class="d-block w-100" alt="...">
      </div>
    </div>
    <p>SignUp to working with us and starting sell yours products and more...<a class="btn btn-lg btn-primary" href="{%url 'DjangoEcommerce:register' %}">SignUp</a></p>
    <hr class="featurette-divider">

    <!-- /END THE FEATURETTES -->

  </div><!-- /.container -->


  <!-- FOOTER -->
  <footer class="container">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2017–2024 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</main>



 {% endblock %}

DjangoE_commerce/DjangoEcommerce/templates/DjangoEcommerce/product_details.html
{%extends 'base.html'%}

{%block content%}

<div id="carouselExample" class="carousel slide">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{{ product.image.url }}" class="d-block w-100" alt="...">
        </div>
        {% if product.image2 %}
        <div class="carousel-item">
            <img src="{{ product.image2.url }}" class="d-block w-100" alt="...">
        </div>
        {% endif %}
        {% if product.image3 %}
        <div class="carousel-item">
            <img src="{{ product.image3.url }}" class="d-block w-100" alt="...">
        </div>
        {% endif %}
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<!--ACCORDION-->
  <div class="accordion accordion-flush" id="accordionFlushExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
          {{product.name}}'s PROPERTIES
        </button>
      </h2>
      <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">With over 160,000 units sold in Europe - and having won the World Supersport Championship 3 times in the last 7 years - the YZF-R6 is on the record as being one of the most popular and extreme supersport bikes that Yamaha have ever built. Light, agile and fast, this iconic 600cc model is the number one choice with today's go-getting thrill seekers who are looking to progress quickly through the supersport ranks.

            To underline the company's total commitment to the supersport segment - which remains a key ingredient in Yamaha's sporty, race bred DNA - the leading Japanese manufacturer will introduce a radically styled new YZF-R6 for 2017, that has been created using some of the latest YZF-R1 derived chassis technology together with cutting edge electronics.
            
            With newly developed low-drag bodywork and an aggressive look that bears all the characteristics of Yamaha's thoroughbred R-series DNA, the new YZF-R6 has arrived.Racing is ouR World. Welcome to R WORLD.With every YZF-R series model there comes an open invitation to enter ouR World, and the chance to become an integral part of one of the most exclusive clubs in the supersportcategory.
            
            In ouR World, racing and winning is a way of life that is deeply embedded within our DNA. In ouR World, every YZF supersport model can trace its lineage straight back to our MotoGP-winning YZR-M1 race bike. And in ouR World we believe in giving everybody the opportunity to experience the real meaning of supersport performance.
            
            No other manufacturer is able to offer such a broad choice of high-tech supersport models from 125cc through to 1,000cc. From the YZF-R1M through to the YZF-R1, YZF-R6, YZF-R3 and YZF-R125, each R-series model is designed and manufactured using the most sophisticated race-bred technology.
            
            R WORLD is open to every rider who appreciates the value of Yamaha's race winning heritage and renowned technical expertise. And R WORLD enables YZF-R series owners the chance to unlock their true riding potential on the street and track.OuR World is here. R WORLD is now. <code>.accordion-flush</code> class. This is the first item's accordion body.</div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
          Accordion Item #2
        </button>
      </h2>
      <div id="flush-collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the second item's accordion body. Let's imagine this being filled with some actual content.</div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
          Accordion Item #3
        </button>
      </h2>
      <div id="flush-collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
        <div class="accordion-body">Placeholder content for this accordion, which is intended to demonstrate the <code>.accordion-flush</code> class. This is the third item's accordion body. Nothing more exciting happening here in terms of content, but just filling up the space to make it look, at least at first glance, a bit more representative of how this would look in a real-world application.</div>
      </div>
    </div>
  </div>
  <a href="{%url 'DjangoEcommerce:orderform'  %}" class="btn btn-primary">Price: {{ product.price }}</a>
  <a class="buy-now-button" href="{% url 'DjangoEcommerce:add_to_cart' product_id=product.id %}">Add to Cart</a>
  

{% endblock %}

DjangoE_commerce/DjangoEcommerce/templates/DjangoEcommerce/products.html
{% extends 'base.html' %}
{%load static%}
{% block content %}
<div class="container" style="width: 50%;">
  {% for product in products %}
  <div class="card" style="width: 18rem,; padding: 10px;">
    {% if product.image %}
      <img src="{{ product.image.url }}" class="card-img-top" alt="">
    {% else %}
      <img src="{% static 'images/default/nofind.jpg' %}" class="card-img-top" alt="Default Image">
      {% endif %}
    <div class="card-body">
      <h5 class="card-title">{{ product.name }}</h5>
      <p class="card-text">DESCRIPTION: {{ product.describtion }}</p>
      <a href="{%url 'DjangoEcommerce:product_details' product_id=product.id %}" class="btn btn-primary">Price: {{ product.price }}</a>
      <a class="buy-now-button" href="{% url 'DjangoEcommerce:add_to_cart' product_id=product.id %}">Add to Cart</a>


      
      
      
      {%if product.username == user%}
        <a href="{%url 'DjangoEcommerce:DeleteProduct' id=product_id%}" class="btn btn-danger">Delete</a>
      
      {%endif%}
      
      
    </div>
    {%if product.username == user%}
  <a href="{%url 'DjangoEcommerce:DeleteProduct' id=product.id%}" class="btn btn-danger">Delete</a>
  
  

  {%endif%}
  </div>
  
  </div>
  {% endfor %}

{% endblock %}



        
    

DjangoE_commerce/templates/base.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <title>DjangoEcommerce</title>
    <link rel="stylesheet" href="{%static 'DjangoEcommerce/customform.css'%}">
    
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">E-Commerce</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'DjangoEcommerce:mainpage'%}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'DjangoEcommerce:addproduct'%}">Add Product</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{%url 'DjangoEcommerce:products'%}">Products</a>
              
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'DjangoEcommerce:cart'%}">Your Cart</a>  
            </li>
            
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'DjangoEcommerce:register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              <li class="nav-item">
                <form class="nav-item" method="post" action="{% url 'logout' %}?next=/">  
                  {% csrf_token %}
                  <button type="submit">Logout</button>
             </form>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link disabled" aria-disabled="true">Disabled</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

      {%block content%}
    {% endblock %}
    
</body>
</html>